- name: configuring shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven and mysql
    package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
  
  - name: create roboshop system user
    user:
     name: roboshop
     system: yes
     home: /app
     shell: /sbin/nologin
     comment: roboshop system user
     state: present

  - name: remove /app directory
    file:
     path: /app
     state: absent
  
  - name: deleting shipping.zip in tmp directory
    file:
      path: /tmp/shipping.zip
      state: absent

  - name: create app directory
    file:
     path: /app
     state: directory

  - name: download shipping application url
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip
  
  - name: unzip file
    unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    command: mvn clean package
    args:
      chdir: /app

  - name: moving shipping jira file
    command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping template
    template:
      src: shipping.service.j2
      dest: /etc/systemd/system/shipping.service

  - name: install python dependencies
    pip:
      name: PyMySQL
      executable: pip3.9

  - name: loading schemas in mysql DB
    community.mysql.mysql_db:
      name: all
      state: import
      target: "{{ item }}"
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

  - name: daemon reload
    systemd_service:
      daemon_reload: yes

  - name: start and enable shipping service
    systemd:
      name: shipping
      enabled: yes
      state: restarted
